### ISSUE TITLE
TODO list of GSoC

### ISSUE THREAD

**Issue by YingboMa** [SciML/BoundaryValueDiffEq.jl#5]
This is a list of TODOs for my GSoC project.

### High priority:
- [x] Shooting methods
  - [x] Testing of shooting methods
- [ ] Collocation method based on MIRK formulae
  - [x] Add convergence tests
  - [x] Match the DiffEq interface
  - [ ] Construct sparsity pattern of the Jacobian matrix of the ODE system
  - [ ] Construct the Jacobian matrix via [ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl)
  - [x] Check type stability of the collocation method
  - [ ] Mesh uniform refinement
  - [ ] Add more MIRK tableaus
- [ ] Benchmark
- [ ] Documentation

### Low priority:
- [ ] Optimization
  - [ ] Use a user's analytical Jacobian matrix
- [ ] Mesh strategy
  - [ ] Adaptive mesh refinement
  - [ ] Adaptive mesh coarsening

**Comment by ChrisRackauckas** [comment]
Add that it should match the DiffEq interface. the `Shooting` method is an example to follow for how to do this.

**Comment by cortner** [comment]
About the `ForwardDiff` jacobian: I am assuming this is applied to `f`, rather than `Phi`?

**Comment by ChrisRackauckas** [comment]
Yeah, having a different setting use Calculus.jl would be recommended. The Jacobian should be built from the Jacobian of `f` anyways, since that's what the user would know how to set in the case an analytical Jacobian is known. So at the bottom it's either Calculus.jl or ForwardDiff.jl on `f`, then building the Jacobian from there.

**Comment by cortner** [comment]
I think finite difference has moved to a separate package - but you are right that is all that is needed

**Comment by ChrisRackauckas** [comment]
FiniteDiff.jl, but I don't think it's ready or registered.

**Comment by avik-pal** [comment]
Closing this. We have all of these now :tada:
